# Exercise 1
- generating 10000 random numbers in a 2-dimensional array
- for each value in the array calculate the square root
- and then sum all those calculations.

In [11]:
import numpy as np

arr = np.random.random((100, 100))
sqrt = np.sqrt(arr)
np.sum(arr)

np.float64(4994.626474359588)

# Exercise 2
Select the following data from the `RandomeValues.csv` file:

- All the data in rows, 5,7 and 9.
- All the data in columns 0, 7, 10.
- The data in columns 1 to 3 (exclusively), from rows 7 to 9 (inclusively).

In [19]:
arr = np.genfromtxt('data/RandomeValues.csv', delimiter=',')
arr[[5,7,9]]
arr[:,[0,7,10]]

arr[7:10,2:3]

array([[10.],
       [ 8.],
       [76.]])

# Exercise 3
Extract from `SalesData.csv` file the column and row headers into two separate arrays. Then extract the data values into a separate 2D array. Using these 3 arrays extract the following data:

- All the sales for the second quarter (Jul-18 to Sep-18 inclusive) calculating the total and the mean for each month.
- All the sales for stores L3 and L1, for the first and third quarter calculating the total and the mean for each quarter for each store.
- All the sales for N6 and N4 that are lower than 400 and list the months in which the occur.

In [75]:
with open('data/SalesData.csv') as file:
    data = [line for line in file.readlines()]
# Because popping is so convenient!
headers = np.array(data.pop(0).strip().split(','))[1:]

data = np.array([line.strip().split(',') for line in data])

index = data[:, 0]

data = np.delete(data, [0], axis=1)
data = data.astype(int)

In [ ]:
q2 = data[:, 3:6].transpose()
q2_sum = q2.sum(axis=0)
q2_mean = q2.mean(axis=0, dtype=int)
q2_mean

array([348, 352, 385, 361, 365, 426])

In [ ]:
L3_L1 = data[1:3, (np.isin(headers, ['Apr-18', 'May-18', 'Jun-18', 
                                     'Oct-18', 'Nov-18', 'Dec-18']))]
L3_L1

array([[392, 377, 347, 340, 446, 573],
       [250, 270, 300, 306, 489, 552]])

In [ ]:
q1_sums = L3_L1[:, :3].sum(axis=1)
q3_sums = L3_L1[:, 3:].sum(axis=1)
q1_means = L3_L1[:, :3].mean(axis=1)
q3_means = L3_L1[:, 3:].mean(axis=1)

In [148]:
n6_n4 = data[(np.isin(index, ['N6', 'N4']))]
months = headers[(n6_n4<400)[0] * (n6_n4<400)[1]]

# Exercise 4
The random walk problem can be used as an interesting investigation into probability. Consider the following:

- A bug lives in the middle of a long thin island where it can only move left or right. The island is 7 units (steps) long. If the bug reaches the edge of the island in either direction it will fall off and drown in the sea. The bug can only move one step in either direction. If the direction is randomly selected how many steps will it take before the bug falls off?
- Investigate ‘random walks’ and using the code in the core text as a starting point write a program to test the above scenario over 100 iterations. Collect the step count in an appropriate structure and then apply appropriate statistics to describe this data.

In [218]:
def walk_fun(iter=500, steps=100):
    rand = np.random.default_rng(4546)
    draws = rand.integers(0, 2, (iter, steps))
    steps = np.where(draws == 0, 1, -1)

    walk = steps.cumsum(axis=1)
    return walk

walk = walk_fun(5000, 200)

reaches_7 = (np.abs(walk) >= 7).any(axis=1)

# Percentage of the iterations that reach 7 steps in either direction
np.count_nonzero(reaches_7) / reaches_7.shape[0]

# Average walk distance of each iteration
walk.mean(axis=1)
# Average cumulative distance of each step
walk.mean(axis=0)
# Average walk distance across 500 walks of length 100
walk.mean()

# Average minimum crossing time of 7 steps over 500 iterations
(np.abs(walk[reaches_7]) >= 7).argmax(axis=1).mean()

np.float64(45.7107704719645)